# blender-nodegraphs-to-xml
# Contributor(s): Tom Schäfer (tschaefer.acc@gmail.com) and Laurin von Bergmann
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

schema_version = "1.0.0"

id = "nodegraphs-to-xml"
version = "1.1.0"
name = "nodegraphs-to-xml"
tagline = "Exports a node-graph (material or nodegroup) into a serialized graph in XML."
maintainer = "Tom Schäfer <tschaefer.acc@gmail.com>, Laurin von Bergmann"
type = "add-on"

website = "https://github.com/Toto-totoro/blender-nodegraphs-to-xml/"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

wheels = [
    "./wheels/lxml-6.1.1-cp313-cp313-win_amd64.whl",
    "./wheels/lxml-6.1.1-cp313-cp313-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl",
    "./wheels/lxml-6.1.1-cp313-cp313-macosx_10_13_universal2.whl"
]